CREATE TABLE `blogs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`blog_id` text NOT NULL,
	`title` text NOT NULL,
	`slug` text NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`category` text NOT NULL,
	`tags` text,
	`author_name` text NOT NULL,
	`author_id` text,
	`featured_image` text,
	`featured_image_alt_text` text,
	`is_featured` integer DEFAULT false NOT NULL,
	`is_published` integer DEFAULT false NOT NULL,
	`views` integer DEFAULT 0 NOT NULL,
	`seo_title` text,
	`seo_description` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`estimated_read_time` integer,
	`scheduled_at` text,
	`comments` integer DEFAULT 0 NOT NULL,
	`upvotes` integer DEFAULT 0 NOT NULL,
	`downvotes` integer DEFAULT 0 NOT NULL,
	`published_at` text NOT NULL,
	`shares` integer DEFAULT 0 NOT NULL,
	`author_bio` text,
	`author_profile_image` text,
	`post_type` text DEFAULT 'regular' NOT NULL,
	`related_blogs` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`external_url` text,
	`featured_image_width` integer,
	`featured_image_height` integer,
	`is_approved` integer DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `blogs_blog_id_unique` ON `blogs` (`blog_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `blogs_slug_unique` ON `blogs` (`slug`);